"""Pack Simulator — product definitions with rarity tiers and pull weights."""

PRODUCTS = {
    # ===== NBA =====
    "2024-25 Donruss Basketball": {
        "sport": "NBA",
        "cards_per_pack": 8,
        "pack_price": 5.00,
        "packs_per_box": 24,
        "box_price": 120.00,
        "description": "Budget-friendly entry point. Rated Rookies, Press Proofs, and Autos.",
        "tiers": [
            {"name": "Base", "weight": 60, "card_type": "Base", "is_hit": False},
            {"name": "Rated Rookie", "weight": 15, "card_type": "Base", "is_hit": False},
            {"name": "Press Proof Silver", "weight": 8, "card_type": "Prizm Silver", "is_hit": True},
            {"name": "Press Proof Blue", "weight": 5, "card_type": "Blue Prizm", "is_hit": True},
            {"name": "Press Proof Red", "weight": 4, "card_type": "Red Prizm", "is_hit": True},
            {"name": "Holo Orange Laser", "weight": 3, "card_type": "Numbered /199", "is_hit": True},
            {"name": "Holo Purple Laser", "weight": 2, "card_type": "Numbered /75", "is_hit": True},
            {"name": "Auto", "weight": 1.5, "card_type": "Auto", "is_hit": True},
            {"name": "Gold Laser /10", "weight": 1, "card_type": "Gold Prizm /10", "is_hit": True},
            {"name": "Downtown", "weight": 0.5, "card_type": "Green Shimmer /25", "is_hit": True},
        ],
    },
    "2024-25 Prizm Basketball Hobby": {
        "sport": "NBA",
        "cards_per_pack": 12,
        "pack_price": 37.50,
        "packs_per_box": 12,
        "box_price": 450.00,
        "description": "The flagship basketball product. Silver Prizms, Color Blasts, and Autos.",
        "tiers": [
            {"name": "Base", "weight": 55, "card_type": "Base", "is_hit": False},
            {"name": "Silver Prizm", "weight": 18, "card_type": "Prizm Silver", "is_hit": True},
            {"name": "Red White Blue", "weight": 8, "card_type": "Red White Blue", "is_hit": True},
            {"name": "Blue Prizm", "weight": 5, "card_type": "Blue Prizm", "is_hit": True},
            {"name": "Red Prizm", "weight": 4, "card_type": "Red Prizm", "is_hit": True},
            {"name": "Numbered /199", "weight": 3, "card_type": "Numbered /199", "is_hit": True},
            {"name": "Auto", "weight": 2, "card_type": "Auto", "is_hit": True},
            {"name": "Numbered /75", "weight": 2, "card_type": "Numbered /75", "is_hit": True},
            {"name": "Gold /10", "weight": 1.5, "card_type": "Gold Prizm /10", "is_hit": True},
            {"name": "Green Shimmer /25", "weight": 1, "card_type": "Green Shimmer /25", "is_hit": True},
            {"name": "1/1 Black", "weight": 0.5, "card_type": "Black 1/1", "is_hit": True},
        ],
    },
    "2024-25 Select Basketball Hobby": {
        "sport": "NBA",
        "cards_per_pack": 10,
        "pack_price": 50.00,
        "packs_per_box": 12,
        "box_price": 600.00,
        "description": "Premium tiers: Concourse, Premier, Courtside. Die-cuts and Autos.",
        "tiers": [
            {"name": "Concourse Base", "weight": 45, "card_type": "Base", "is_hit": False},
            {"name": "Premier Level", "weight": 15, "card_type": "Base", "is_hit": False},
            {"name": "Courtside Level", "weight": 10, "card_type": "Prizm Silver", "is_hit": True},
            {"name": "Silver Prizm", "weight": 8, "card_type": "Prizm Silver", "is_hit": True},
            {"name": "Tri-Color Prizm", "weight": 5, "card_type": "Red White Blue", "is_hit": True},
            {"name": "Blue Prizm /249", "weight": 4, "card_type": "Blue Prizm", "is_hit": True},
            {"name": "Purple Prizm /99", "weight": 3.5, "card_type": "Numbered /199", "is_hit": True},
            {"name": "Orange Prizm /75", "weight": 3, "card_type": "Numbered /75", "is_hit": True},
            {"name": "Auto", "weight": 2.5, "card_type": "Auto", "is_hit": True},
            {"name": "Gold Prizm /10", "weight": 2, "card_type": "Gold Prizm /10", "is_hit": True},
            {"name": "Green Prizm /5", "weight": 1, "card_type": "Green Shimmer /25", "is_hit": True},
            {"name": "Black 1/1", "weight": 0.5, "card_type": "Black 1/1", "is_hit": True},
            {"name": "Tie-Dye /25", "weight": 0.5, "card_type": "Green Shimmer /25", "is_hit": True},
        ],
    },

    # ===== NFL =====
    "2024 Donruss Football": {
        "sport": "NFL",
        "cards_per_pack": 8,
        "pack_price": 5.00,
        "packs_per_box": 24,
        "box_price": 120.00,
        "description": "Rated Rookies and Press Proofs at an affordable price point.",
        "tiers": [
            {"name": "Base", "weight": 60, "card_type": "Base", "is_hit": False},
            {"name": "Rated Rookie", "weight": 15, "card_type": "Base", "is_hit": False},
            {"name": "Press Proof Silver", "weight": 8, "card_type": "Prizm Silver", "is_hit": True},
            {"name": "Press Proof Blue", "weight": 5, "card_type": "Blue Prizm", "is_hit": True},
            {"name": "Press Proof Red", "weight": 4, "card_type": "Red Prizm", "is_hit": True},
            {"name": "Holo Orange Laser", "weight": 3, "card_type": "Numbered /199", "is_hit": True},
            {"name": "Holo Purple Laser", "weight": 2, "card_type": "Numbered /75", "is_hit": True},
            {"name": "Auto", "weight": 1.5, "card_type": "Auto", "is_hit": True},
            {"name": "Gold Laser /10", "weight": 1, "card_type": "Gold Prizm /10", "is_hit": True},
            {"name": "Downtown", "weight": 0.5, "card_type": "Green Shimmer /25", "is_hit": True},
        ],
    },
    "2024 Prizm Football Hobby": {
        "sport": "NFL",
        "cards_per_pack": 12,
        "pack_price": 25.00,
        "packs_per_box": 12,
        "box_price": 300.00,
        "description": "Caleb Williams, Jayden Daniels, and the rookie class. Silver Prizms and Autos.",
        "tiers": [
            {"name": "Base", "weight": 55, "card_type": "Base", "is_hit": False},
            {"name": "Silver Prizm", "weight": 18, "card_type": "Prizm Silver", "is_hit": True},
            {"name": "Red White Blue", "weight": 8, "card_type": "Red White Blue", "is_hit": True},
            {"name": "Blue Prizm", "weight": 5, "card_type": "Blue Prizm", "is_hit": True},
            {"name": "Red Prizm", "weight": 4, "card_type": "Red Prizm", "is_hit": True},
            {"name": "Numbered /199", "weight": 3, "card_type": "Numbered /199", "is_hit": True},
            {"name": "Auto", "weight": 2, "card_type": "Auto", "is_hit": True},
            {"name": "Numbered /75", "weight": 2, "card_type": "Numbered /75", "is_hit": True},
            {"name": "Gold /10", "weight": 1.5, "card_type": "Gold Prizm /10", "is_hit": True},
            {"name": "Green Shimmer /25", "weight": 1, "card_type": "Green Shimmer /25", "is_hit": True},
            {"name": "1/1 Black", "weight": 0.5, "card_type": "Black 1/1", "is_hit": True},
        ],
    },
    "2024 Mosaic Football": {
        "sport": "NFL",
        "cards_per_pack": 10,
        "pack_price": 15.00,
        "packs_per_box": 12,
        "box_price": 180.00,
        "description": "Mosaic parallels with a stained-glass look. Mid-range hobby hit.",
        "tiers": [
            {"name": "Base", "weight": 55, "card_type": "Base", "is_hit": False},
            {"name": "Silver Mosaic", "weight": 16, "card_type": "Prizm Silver", "is_hit": True},
            {"name": "Blue Mosaic", "weight": 8, "card_type": "Blue Prizm", "is_hit": True},
            {"name": "Green Mosaic", "weight": 5, "card_type": "Red White Blue", "is_hit": True},
            {"name": "Red Mosaic", "weight": 4, "card_type": "Red Prizm", "is_hit": True},
            {"name": "Purple /99", "weight": 3.5, "card_type": "Numbered /199", "is_hit": True},
            {"name": "Gold /10", "weight": 2.5, "card_type": "Gold Prizm /10", "is_hit": True},
            {"name": "Auto", "weight": 2.5, "card_type": "Auto", "is_hit": True},
            {"name": "Fluorescent /25", "weight": 2, "card_type": "Green Shimmer /25", "is_hit": True},
            {"name": "Genesis /1", "weight": 1, "card_type": "Superfractor 1/1", "is_hit": True},
            {"name": "Stained Glass", "weight": 0.5, "card_type": "Hyper Rare", "is_hit": True},
        ],
    },

    # ===== MLB =====
    "2024 Topps Series 1 Baseball": {
        "sport": "MLB",
        "cards_per_pack": 14,
        "pack_price": 5.00,
        "packs_per_box": 24,
        "box_price": 120.00,
        "description": "The original. Flagship Topps with rookies, relics, and autos.",
        "tiers": [
            {"name": "Base", "weight": 65, "card_type": "Base", "is_hit": False},
            {"name": "Parallel", "weight": 12, "card_type": "Refractor", "is_hit": True},
            {"name": "Rainbow Foil", "weight": 7, "card_type": "Refractor", "is_hit": True},
            {"name": "Gold /2024", "weight": 4, "card_type": "Gold Refractor /50", "is_hit": True},
            {"name": "Vintage Stock /99", "weight": 3, "card_type": "Green Refractor /99", "is_hit": True},
            {"name": "Independence Day /76", "weight": 2.5, "card_type": "Blue Refractor /199", "is_hit": True},
            {"name": "Auto", "weight": 2.5, "card_type": "Auto", "is_hit": True},
            {"name": "Relic", "weight": 2, "card_type": "Auto", "is_hit": True},
            {"name": "Platinum 1/1", "weight": 1, "card_type": "Superfractor 1/1", "is_hit": True},
            {"name": "Printing Plate 1/1", "weight": 1, "card_type": "Superfractor 1/1", "is_hit": True},
        ],
    },
    "2024 Topps Chrome Baseball Hobby": {
        "sport": "MLB",
        "cards_per_pack": 4,
        "pack_price": 15.00,
        "packs_per_box": 24,
        "box_price": 360.00,
        "description": "Chrome refractors, rookie autos, and color parallels.",
        "tiers": [
            {"name": "Base", "weight": 55, "card_type": "Base", "is_hit": False},
            {"name": "Refractor", "weight": 18, "card_type": "Refractor", "is_hit": True},
            {"name": "Blue Refractor /199", "weight": 7, "card_type": "Blue Refractor /199", "is_hit": True},
            {"name": "Green Refractor /99", "weight": 5, "card_type": "Green Refractor /99", "is_hit": True},
            {"name": "Gold Refractor /50", "weight": 4, "card_type": "Gold Refractor /50", "is_hit": True},
            {"name": "Numbered /25", "weight": 3, "card_type": "Orange Refractor /25", "is_hit": True},
            {"name": "Auto", "weight": 3, "card_type": "Auto", "is_hit": True},
            {"name": "Red Refractor /5", "weight": 2, "card_type": "Red Refractor /5", "is_hit": True},
            {"name": "Auto Refractor", "weight": 1.5, "card_type": "Auto Refractor", "is_hit": True},
            {"name": "Gold Auto /50", "weight": 1, "card_type": "Gold Auto /50", "is_hit": True},
            {"name": "Superfractor 1/1", "weight": 0.5, "card_type": "Superfractor 1/1", "is_hit": True},
        ],
    },
    "2024 Bowman Baseball Hobby": {
        "sport": "MLB",
        "cards_per_pack": 10,
        "pack_price": 20.00,
        "packs_per_box": 24,
        "box_price": 480.00,
        "description": "The prospect product. 1st Bowman Chrome cards of future stars.",
        "tiers": [
            {"name": "Base", "weight": 50, "card_type": "Base", "is_hit": False},
            {"name": "1st Chrome", "weight": 15, "card_type": "Refractor", "is_hit": True},
            {"name": "Refractor", "weight": 10, "card_type": "Refractor", "is_hit": True},
            {"name": "Blue Refractor /150", "weight": 5, "card_type": "Blue Refractor /199", "is_hit": True},
            {"name": "Green Refractor /99", "weight": 4, "card_type": "Green Refractor /99", "is_hit": True},
            {"name": "Gold Refractor /50", "weight": 3.5, "card_type": "Gold Refractor /50", "is_hit": True},
            {"name": "1st Chrome Auto", "weight": 4, "card_type": "Auto", "is_hit": True},
            {"name": "Orange Refractor /25", "weight": 3, "card_type": "Orange Refractor /25", "is_hit": True},
            {"name": "Auto Refractor", "weight": 2.5, "card_type": "Auto Refractor", "is_hit": True},
            {"name": "Red Refractor /5", "weight": 1.5, "card_type": "Red Refractor /5", "is_hit": True},
            {"name": "Gold Auto /50", "weight": 1, "card_type": "Gold Auto /50", "is_hit": True},
            {"name": "Superfractor 1/1", "weight": 0.5, "card_type": "Superfractor 1/1", "is_hit": True},
        ],
    },

    # ===== Pokemon =====
    "Scarlet & Violet 151 Pokemon": {
        "sport": "Pokemon",
        "cards_per_pack": 10,
        "pack_price": 8.00,
        "packs_per_box": 36,
        "box_price": 288.00,
        "description": "The original 151 Pokemon. Chase the Charizard ex illustration rare.",
        "tiers": [
            {"name": "Common", "weight": 45, "card_type": "Common", "is_hit": False},
            {"name": "Uncommon", "weight": 20, "card_type": "Uncommon", "is_hit": False},
            {"name": "Holo Rare", "weight": 12, "card_type": "Holo Rare", "is_hit": True},
            {"name": "Reverse Holo", "weight": 8, "card_type": "Reverse Holo", "is_hit": False},
            {"name": "ex Card", "weight": 5, "card_type": "ex", "is_hit": True},
            {"name": "Full Art", "weight": 4, "card_type": "Full Art", "is_hit": True},
            {"name": "Illustration Rare", "weight": 3, "card_type": "Illustration Rare", "is_hit": True},
            {"name": "Special Art Rare", "weight": 1.5, "card_type": "Special Art Rare", "is_hit": True},
            {"name": "Ultra Rare", "weight": 1, "card_type": "Ultra Rare", "is_hit": True},
            {"name": "Hyper Rare", "weight": 0.5, "card_type": "Hyper Rare", "is_hit": True},
        ],
    },
    "Obsidian Flames Pokemon": {
        "sport": "Pokemon",
        "cards_per_pack": 10,
        "pack_price": 5.00,
        "packs_per_box": 36,
        "box_price": 180.00,
        "description": "Charizard ex returns. Obsidian art style with Tera Pokemon.",
        "tiers": [
            {"name": "Common", "weight": 48, "card_type": "Common", "is_hit": False},
            {"name": "Uncommon", "weight": 20, "card_type": "Uncommon", "is_hit": False},
            {"name": "Holo Rare", "weight": 10, "card_type": "Holo Rare", "is_hit": True},
            {"name": "Reverse Holo", "weight": 8, "card_type": "Reverse Holo", "is_hit": False},
            {"name": "ex Card", "weight": 5, "card_type": "ex", "is_hit": True},
            {"name": "Full Art", "weight": 3.5, "card_type": "Full Art", "is_hit": True},
            {"name": "Illustration Rare", "weight": 2.5, "card_type": "Illustration Rare", "is_hit": True},
            {"name": "Special Art Rare", "weight": 1.5, "card_type": "Special Art Rare", "is_hit": True},
            {"name": "Ultra Rare", "weight": 1, "card_type": "Ultra Rare", "is_hit": True},
            {"name": "Hyper Rare", "weight": 0.5, "card_type": "Hyper Rare", "is_hit": True},
        ],
    },
    "Paldea Evolved Pokemon": {
        "sport": "Pokemon",
        "cards_per_pack": 10,
        "pack_price": 5.00,
        "packs_per_box": 36,
        "box_price": 180.00,
        "description": "Gen 9 Paldea starters evolve. Chase the Iono Full Art.",
        "tiers": [
            {"name": "Common", "weight": 48, "card_type": "Common", "is_hit": False},
            {"name": "Uncommon", "weight": 20, "card_type": "Uncommon", "is_hit": False},
            {"name": "Holo Rare", "weight": 10, "card_type": "Holo Rare", "is_hit": True},
            {"name": "Reverse Holo", "weight": 8, "card_type": "Reverse Holo", "is_hit": False},
            {"name": "ex Card", "weight": 5, "card_type": "ex", "is_hit": True},
            {"name": "Full Art", "weight": 3.5, "card_type": "Full Art", "is_hit": True},
            {"name": "Illustration Rare", "weight": 2.5, "card_type": "Illustration Rare", "is_hit": True},
            {"name": "Special Art Rare", "weight": 1.5, "card_type": "Special Art Rare", "is_hit": True},
            {"name": "Ultra Rare", "weight": 1, "card_type": "Ultra Rare", "is_hit": True},
            {"name": "Hyper Rare", "weight": 0.5, "card_type": "Hyper Rare", "is_hit": True},
        ],
    },
}

# Products available on free tier
FREE_PRODUCTS = [
    "2024-25 Donruss Basketball",
    "2024 Donruss Football",
    "2024 Topps Series 1 Baseball",
    "Scarlet & Violet 151 Pokemon",
    "Obsidian Flames Pokemon",
    "Paldea Evolved Pokemon",
]
