"""Pack Simulator — product definitions with rarity tiers and pull weights."""

PRODUCTS = {
    "2024-25 Prizm Basketball Hobby": {
        "sport": "NBA",
        "cards_per_pack": 12,
        "pack_price": 37.50,
        "packs_per_box": 12,
        "box_price": 450.00,
        "description": "The flagship basketball product. Silver Prizms, Color Blasts, and Autos.",
        "tiers": [
            {"name": "Base", "weight": 55, "card_type": "Base", "is_hit": False},
            {"name": "Silver Prizm", "weight": 18, "card_type": "Prizm Silver", "is_hit": True},
            {"name": "Red White Blue", "weight": 8, "card_type": "Red White Blue", "is_hit": True},
            {"name": "Blue Prizm", "weight": 5, "card_type": "Blue Prizm", "is_hit": True},
            {"name": "Red Prizm", "weight": 4, "card_type": "Red Prizm", "is_hit": True},
            {"name": "Numbered /199", "weight": 3, "card_type": "Numbered /199", "is_hit": True},
            {"name": "Auto", "weight": 2, "card_type": "Auto", "is_hit": True},
            {"name": "Numbered /75", "weight": 2, "card_type": "Numbered /75", "is_hit": True},
            {"name": "Gold /10", "weight": 1.5, "card_type": "Gold Prizm /10", "is_hit": True},
            {"name": "Green Shimmer /25", "weight": 1, "card_type": "Green Shimmer /25", "is_hit": True},
            {"name": "1/1 Black", "weight": 0.5, "card_type": "Black 1/1", "is_hit": True},
        ],
    },
    "2024 Prizm Football Hobby": {
        "sport": "NFL",
        "cards_per_pack": 12,
        "pack_price": 25.00,
        "packs_per_box": 12,
        "box_price": 300.00,
        "description": "Caleb Williams, Jayden Daniels, and the rookie class. Silver Prizms and Autos.",
        "tiers": [
            {"name": "Base", "weight": 55, "card_type": "Base", "is_hit": False},
            {"name": "Silver Prizm", "weight": 18, "card_type": "Prizm Silver", "is_hit": True},
            {"name": "Red White Blue", "weight": 8, "card_type": "Red White Blue", "is_hit": True},
            {"name": "Blue Prizm", "weight": 5, "card_type": "Blue Prizm", "is_hit": True},
            {"name": "Red Prizm", "weight": 4, "card_type": "Red Prizm", "is_hit": True},
            {"name": "Numbered /199", "weight": 3, "card_type": "Numbered /199", "is_hit": True},
            {"name": "Auto", "weight": 2, "card_type": "Auto", "is_hit": True},
            {"name": "Numbered /75", "weight": 2, "card_type": "Numbered /75", "is_hit": True},
            {"name": "Gold /10", "weight": 1.5, "card_type": "Gold Prizm /10", "is_hit": True},
            {"name": "Green Shimmer /25", "weight": 1, "card_type": "Green Shimmer /25", "is_hit": True},
            {"name": "1/1 Black", "weight": 0.5, "card_type": "Black 1/1", "is_hit": True},
        ],
    },
    "2024 Topps Chrome Baseball Hobby": {
        "sport": "MLB",
        "cards_per_pack": 4,
        "pack_price": 15.00,
        "packs_per_box": 24,
        "box_price": 360.00,
        "description": "Chrome refractors, rookie autos, and color parallels.",
        "tiers": [
            {"name": "Base", "weight": 55, "card_type": "Base", "is_hit": False},
            {"name": "Refractor", "weight": 18, "card_type": "Refractor", "is_hit": True},
            {"name": "Blue Refractor /199", "weight": 7, "card_type": "Blue Refractor /199", "is_hit": True},
            {"name": "Green Refractor /99", "weight": 5, "card_type": "Green Refractor /99", "is_hit": True},
            {"name": "Gold Refractor /50", "weight": 4, "card_type": "Gold Refractor /50", "is_hit": True},
            {"name": "Numbered /25", "weight": 3, "card_type": "Orange Refractor /25", "is_hit": True},
            {"name": "Auto", "weight": 3, "card_type": "Auto", "is_hit": True},
            {"name": "Red Refractor /5", "weight": 2, "card_type": "Red Refractor /5", "is_hit": True},
            {"name": "Auto Refractor", "weight": 1.5, "card_type": "Auto Refractor", "is_hit": True},
            {"name": "Gold Auto /50", "weight": 1, "card_type": "Gold Auto /50", "is_hit": True},
            {"name": "Superfractor 1/1", "weight": 0.5, "card_type": "Superfractor 1/1", "is_hit": True},
        ],
    },
    "Scarlet & Violet 151 Pokemon": {
        "sport": "Pokemon",
        "cards_per_pack": 10,
        "pack_price": 8.00,
        "packs_per_box": 36,
        "box_price": 288.00,
        "description": "The original 151 Pokemon. Chase the Charizard ex illustration rare.",
        "tiers": [
            {"name": "Common", "weight": 45, "card_type": "Common", "is_hit": False},
            {"name": "Uncommon", "weight": 20, "card_type": "Uncommon", "is_hit": False},
            {"name": "Holo Rare", "weight": 12, "card_type": "Holo Rare", "is_hit": True},
            {"name": "Reverse Holo", "weight": 8, "card_type": "Reverse Holo", "is_hit": False},
            {"name": "ex Card", "weight": 5, "card_type": "ex", "is_hit": True},
            {"name": "Full Art", "weight": 4, "card_type": "Full Art", "is_hit": True},
            {"name": "Illustration Rare", "weight": 3, "card_type": "Illustration Rare", "is_hit": True},
            {"name": "Special Art Rare", "weight": 1.5, "card_type": "Special Art Rare", "is_hit": True},
            {"name": "Ultra Rare", "weight": 1, "card_type": "Ultra Rare", "is_hit": True},
            {"name": "Hyper Rare", "weight": 0.5, "card_type": "Hyper Rare", "is_hit": True},
        ],
    },
}

# Products available on free tier (first 3)
FREE_PRODUCTS = [
    "2024-25 Prizm Basketball Hobby",
    "2024 Prizm Football Hobby",
    "Scarlet & Violet 151 Pokemon",
]
